blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions
    url: https://github.com/xelaj/tl/discussions
    about: Please ask and answer questions here.
  # # github doesn't allow to tune security template... no emojis ğŸ˜­
  # - name: ğŸ” Security issue
  #   url: https://github.com/xelaj/tl/blob/-/.github/SECURITY.md
  #   about: Report of any security vulnerabilities here.
  - name: ğŸ— Support
    url: https://github.com//xelaj/tl/blob/-/.github/SUPPORT.md
    about: Support this project without writing code
